### ISSUE TITLE
License Issue

### ISSUE THREAD

**Issue by SanderElias** [rlidwka/jju#28]
It turns out the WTFPL has no legal state. This is preventing some projects from using your code.
Would you be willing to change your licence to MIT? it will make it possible to use this library in a corporate environment.

**Comment by JustinBeckwith** [comment]
This is causing us some issues as well. It would be great to see this distributed under the MIT license.

**Comment by light24bulbs** [comment]
Please change your license to MIT or something.  The point of your license is to be permissive, and because of the legalese, it actually isn't.

**Comment by spectejb** [comment]
@rlidwka Would love to hear your thoughts on the above requests.  It sounds like a lot of corporations are taking a strong stance against use of open source with a WTFPL license (mine included :/ )

I am no expert but taking a look at those two, MIT gives people a lot of freedom to use the software how they want and it is recognized by the community (e.g. OSI) which should make people more comfortable using it.  Plus it doesn't hurt that you get the protection from MIT's last paragraph.

Thanks, in advance, for your consideration!

**Comment by SanthiSridharan** [comment]
Hi 
I agree with all of the comments regarding the license. The intent is to make the code open and available for everyone to use without constraints - And WTFPL is actually working against it. So why shouldn’t this be licensed under a commonly used more permissive license ? Like MIT or Apache.

**Comment by spectejb** [comment]
Shout out to @rlidwka for agreeing to add the MIT license!  A great example of someone exhibiting a true open source collaborative mindset.  Cannot wait to see it added to the license file :)

**Comment by rlidwka** [comment]
Changed to MIT, published to npm as 1.4.0. Sorry for the delay, and I sincerely hope that previous license saying "you can use this software" didn't prevent anyone from using it. :)

**Comment by rlidwka** [comment]
That being said, ...

> You're making a world of pain for people trapped in a corporate environment who have to talk to lawyers for hours about this stuff.

I *would* like to talk to lawyers about this stuff. They're probably not reading it, so I imagine this to be more like a monologue. And I have something wonderful to show them. Imagine a gateway sign that reads "Welcome to another world!".

It feels unusual here, completely different from the world you were born in. You can't fully experience it with a human eye, all you see are shadows on your computer screen. But believe me, it is there. And it has the life of its own.

An alien planet. It has plenty of space to live in (3.7 billion, not even counting NAT and IPv6). It has some native life (one that you are sure to meet if you turn off your firewall). It doesn't have countries. It doesn't have government. But arguably, Earth shouldn't have those either.

Here, electrons move at around 300 million m/s, and there are no cops to write a speeding ticket. The laws are different. US consitution worth nothing more than 50kB of disk space used to store it. But don't worry, the same rights are guaranteed by other means.

If you write a private email to someone, can a third party read it? 4th amendment says they can't, but every single server on the way will open it, copy it to its memory, and change it by adding Via headers and such. Google had "amended" this amendment many times in their ToS, and NSA doesn't even pretend to care.

But what happens if you encrypt said email with GPG and such? Then only recipient will have the right to open it. Three-letter agencies can have a dozen PATRIOT acts at their disposal, and they won't be able to read its contents. Do you realize why? Laws are different here!

There are only few books you have to read about it. I'm sure you heard of those two. One governing the hardware (those are laws of physics) and one for software (and that's of course cryptography).

So when you meet a lawyer to tell them the wonderful news of a license change, please show them those books. And ask them: "*That's the Law internet has. It enforces itself. So what do we need you guys for?*".

**Comment by spectejb** [comment]
I'll pass the monologue along :) 

Thanks again @rlidwka!
